In [5]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
d = np.array([[0,1,2],[1,0,0],[2,0,0]])
dNew = csr_matrix(d)
print (connected_components(dNew))

(1, array([0, 0, 0], dtype=int32))


In [6]:
#Dijkstra method

In [7]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
d = np.array([[0,1,2],[1,0,0],[2,0,0]])
dNew = csr_matrix(d)
print (dijkstra(dNew , return_predecessors = True , indices = 0))


(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [8]:
#Floyd Warshall

In [9]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
d = np.array([[0,1,2],[1,0,0],[2,0,0]])
dNew = csr_matrix(d)
print (floyd_warshall(dNew , return_predecessors = True))


(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [ ]:
#Bellman_Ford

In [13]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix
d = np.array([[0,-1,2],[1,0,0],[2,0,0]])
dNew = csr_matrix(d)
print (bellman_ford(dNew , return_predecessors = True , indices = 0))


(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))


In [14]:
#Depth_First_Order

In [18]:
import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix
d = np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
dNew = csr_matrix(d)
print (depth_first_order(dNew , 1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


In [19]:
#breadth_first_order

In [20]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix
d = np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
dNew = csr_matrix(d)
print (breadth_first_order(dNew , 1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))
